### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by Yuancheng12** [bigsinger/Farm#1]
图片等无法显示
![image](https://user-images.githubusercontent.com/30713828/80091460-b9ac8780-8593-11ea-906c-44412a07672f.png)

**Comment by bigsinger** [comment]
缺少什么文件？我传一下

**Comment by Yuancheng12** [comment]
哈哈哈，小问题，本cocos creator的初学者发现大佬的.meta文件都没有传上来，导致导入文件后资源都找不到，即由于原项目缺少配套的.meta文件，导入cocos creator后会自动生成.meta并重新赋予一个uuid，这样就和原项目绑定的各uuid不一致导致资源找不到。(或许你会想知道原因）

—感谢回复

**Comment by bigsinger** [comment]
好吧 我不是游戏从业者 我以为这些文件并不是必须的呢 我传一下

**Comment by bigsinger** [comment]
不好意思 传不了了，我本地电脑上工程已经删除了，cocos相关的软件都卸载了。之前我有确认过把meta文件都删除，然后重新打开工程，工程会自动生成的，你再试下看看？

**Comment by Yuancheng12** [comment]
没事啦 我只是本地运行看一看 并不做实际运用
